# Generated by Django 5.2.1 on 2025-06-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CATEGORY_code', models.CharField(max_length=4, unique=True)),
                ('CATEGORY_description', models.CharField(max_length=100)),
                ('CATEGORY_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CUSTOMER_code', models.CharField(max_length=15, unique=True)),
                ('CUSTOMER_group', models.IntegerField()),
                ('CUSTOMER_area', models.IntegerField()),
                ('CUSTOMER_name', models.CharField(max_length=150)),
                ('CUSTOMER_title', models.CharField(blank=True, max_length=20, null=True)),
                ('CUSTOMER_title_id', models.IntegerField(blank=True, null=True)),
                ('CUSTOMER_address', models.CharField(blank=True, max_length=400, null=True)),
                ('CUSTOMER_tele_1', models.CharField(blank=True, max_length=50, null=True)),
                ('CUSTOMER_tele_2', models.CharField(blank=True, max_length=50, null=True)),
                ('CUSTOMER_tele_mobile', models.CharField(blank=True, max_length=50, null=True)),
                ('CUSTOMER_fax', models.CharField(blank=True, max_length=50, null=True)),
                ('CUSTOMER_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('CUSTOMER_contact_person', models.CharField(blank=True, max_length=150, null=True)),
                ('CUSTOMER_contact_person_title', models.CharField(blank=True, max_length=20, null=True)),
                ('CUSTOMER_contact_person_title_id', models.IntegerField(blank=True, null=True)),
                ('CUSTOMER_term', models.IntegerField()),
                ('CUSTOMER_vat_number', models.CharField(blank=True, max_length=20, null=True)),
                ('CUSTOMER_credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True)),
                ('CUSTOMER_creidt_period', models.BigIntegerField(blank=True, null=True)),
                ('CUSTOMER_account_number', models.IntegerField()),
                ('CUSTOMER_lock', models.BooleanField(default=False)),
                ('CUSTOMER_created_user_session', models.BigIntegerField(blank=True, null=True)),
                ('CUSTOMER_created_datetime', models.DateTimeField(blank=True, null=True)),
                ('CUSTOMER_last_edited_user_session', models.BigIntegerField(blank=True, null=True)),
                ('CUSTOMER_last_edited_datetime', models.DateTimeField(blank=True, null=True)),
                ('CUSTOMER_prefix_id', models.BigIntegerField()),
                ('CUSTOMER_prefix_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GroupMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GROUP_code', models.CharField(max_length=10, unique=True)),
                ('GROUP_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemLocationMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LOC_code', models.CharField(blank=True, max_length=5, null=True)),
                ('LOC_description', models.CharField(blank=True, max_length=200, null=True)),
                ('LOC_address', models.CharField(blank=True, max_length=300, null=True)),
                ('LOC_active', models.BooleanField(default=True)),
                ('LOC_have_maintenance', models.BooleanField(default=False)),
                ('LOC_last_invoice_number', models.BigIntegerField(default=0)),
                ('LOC_invoice_prefix', models.CharField(max_length=1)),
                ('LOC_has_invoice', models.BooleanField(default=False)),
                ('LOC_last_cash_in_hand_number', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('SUPPLIER_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('SUPPLIER_code', models.CharField(max_length=15, unique=True)),
                ('SUPPLIER_group', models.IntegerField()),
                ('SUPPLIER_area', models.IntegerField()),
                ('SUPPLIER_name', models.CharField(max_length=150)),
                ('SUPPLIER_title', models.CharField(blank=True, max_length=20, null=True)),
                ('SUPPLIER_title_id', models.IntegerField(blank=True, null=True)),
                ('SUPPLIER_address', models.CharField(max_length=400)),
                ('SUPPLIER_tele_1', models.CharField(blank=True, max_length=50, null=True)),
                ('SUPPLIER_tele_2', models.CharField(blank=True, max_length=50, null=True)),
                ('SUPPLIER_tele_mobile', models.CharField(blank=True, max_length=50, null=True)),
                ('SUPPLIER_fax', models.CharField(blank=True, max_length=50, null=True)),
                ('SUPPLIER_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('SUPPLIER_contact_person', models.CharField(blank=True, max_length=150, null=True)),
                ('SUPPLIER_contact_person_title', models.CharField(blank=True, max_length=20, null=True)),
                ('SUPPLIER_contact_person_title_id', models.IntegerField(blank=True, null=True)),
                ('SUPPLIER_term', models.IntegerField()),
                ('SUPPLIER_vat_number', models.CharField(blank=True, max_length=20, null=True)),
                ('SUPPLIER_credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True)),
                ('SUPPLIER_creidt_period', models.BigIntegerField(blank=True, null=True)),
                ('SUPPLIER_account_number', models.IntegerField()),
                ('SUPPLIER_lock', models.BooleanField(default=False)),
                ('SUPPLIER_created_user_session', models.BigIntegerField(blank=True, null=True)),
                ('SUPPLIER_created_datetime', models.DateTimeField(blank=True, null=True)),
                ('SUPPLIER_last_edited_user_session', models.BigIntegerField(blank=True, null=True)),
                ('SUPPLIER_last_edited_datetime', models.DateTimeField(blank=True, null=True)),
                ('SUPPLIER_prefix_id', models.BigIntegerField()),
                ('SUPPLIER_prefix_number', models.IntegerField()),
                ('SUPPLIER_customer', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TYPE_code', models.CharField(max_length=4, unique=True)),
                ('TYPE_description', models.CharField(max_length=100)),
                ('TYPE_active', models.BooleanField(default=True)),
                ('TYPE_use_order_form', models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
