# Generated by Django 5.2.1 on 2025-05-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TYPE_code', models.CharField(max_length=4, unique=True)),
                ('TYPE_description', models.CharField(max_length=100)),
                ('TYPE_active', models.BooleanField(default=True)),
                ('TYPE_use_order_form', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
