# Generated by Django 5.2.1 on 2025-06-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockcontrol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMaster',
            fields=[
                ('ITEM_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ITEM_code', models.CharField(max_length=10, unique=True)),
                ('ITEM_group', models.IntegerField()),
                ('ITEM_type', models.IntegerField()),
                ('ITEM_category', models.IntegerField()),
                ('ITEM_description', models.CharField(blank=True, max_length=600, null=True)),
                ('ITEM_uom', models.IntegerField(blank=True, null=True)),
                ('ITEM_reorder_level', models.DecimalField(blank=True, decimal_places=3, max_digits=23, null=True)),
                ('ITEM_reorder_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=23, null=True)),
                ('ITEM_max_level', models.DecimalField(blank=True, decimal_places=3, max_digits=23, null=True)),
                ('ITEM_min_level', models.DecimalField(blank=True, decimal_places=3, max_digits=23, null=True)),
                ('ITEM_purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True)),
                ('ITEM_min_selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True)),
                ('ITEM_normal_selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True)),
                ('ITEM_cash_selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True)),
                ('ITEM_credit_selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True)),
                ('ITEM_invoicable', models.BooleanField(blank=True, null=True)),
                ('ITEM_active', models.BooleanField(blank=True, null=True)),
                ('ITEM_warranty', models.IntegerField(blank=True, null=True)),
                ('ITEM_has_barcode', models.BooleanField(blank=True, null=True)),
                ('ITEM_barcode', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'INV_Item_Master',
                'managed': True,
            },
        ),
    ]
