# Generated by Django 5.2.1 on 2025-05-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockcontrol', '0002_groupmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CATEGORY_code', models.CharField(max_length=4, unique=True)),
                ('CATEGORY_description', models.CharField(max_length=100)),
                ('CATEGORY_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='typemaster',
            name='TYPE_use_order_form',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
